### ISSUE TITLE
isAllowedChatMessage error

### ISSUE THREAD

**Issue by farisrwx** [germanrcuriel/assetto-corsa-server-udp2ws#6]
Last release and i get this error everytime i try socket.on('chat', (data) => {

    Reflect.apply(handler, this, args);
            ^

ReferenceError: isAllowedChatMessage is not defined
    at ACSP.onChat (/snapshot/assetto-corsa-server-udp2ws/lib/udp/acsp.js:0:0)
    at ACSP.onSockMessage (/snapshot/assetto-corsa-server-udp2ws/lib/udp/acsp.js:0:0)
    at Socket.emit (events.js:196:13)
    at UDP.onMessage [as onmessage] (dgram.js:849:8)
events.js:196: command not found

**Comment by germanrcuriel** [comment]
I'll take a look ASAP! Thanks for the report

**Comment by germanrcuriel** [comment]
Fixed in [latest release](https://github.com/germanrcuriel/assetto-corsa-server-udp2ws/releases/tag/v0.3.3)

**Comment by farisrwx** [comment]
Thank you.
