### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by farisrwx** [germanrcuriel/assetto-corsa-server-udp2ws#7]
Hi,
Now when i call socket.on('chat', (data) => {
I get this error:

events.js:210
    apply(handler, this, args);
    ^

TypeError: undefined is not a function
    at ACSP.isAllowedChatMessage (/snapshot/assetto-corsa-server-udp2ws/lib/udp/acsp.js)
    at ACSP.onChat (/snapshot/assetto-corsa-server-udp2ws/lib/udp/acsp.js)
    at ACSP.onSockMessage (/snapshot/assetto-corsa-server-udp2ws/lib/udp/acsp.js)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage [as onmessage] (dgram.js:861:8)

I'm on latest.

edit: when someone type anything in game chat the error appears. ^^

**Comment by germanrcuriel** [comment]
I'll take a look ASAP

**Comment by farisrwx** [comment]
Sorry for mention, any updates?

**Comment by germanrcuriel** [comment]
Had no time to test it yet! Hopefully I'll fix it before the weekend

**Comment by farisrwx** [comment]
Alright no problem! take your time 🙏

**Comment by germanrcuriel** [comment]
Fixed in latest release [v0.3.4](https://github.com/germanrcuriel/assetto-corsa-server-udp2ws/releases/tag/v0.3.4)
